const CHUNK_PUBLIC_PATH = "server/app/dashboard/(overview)/page.js";
const runtime = require("../../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/a7abb_next_dist_a817a3._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__592060._.js");
runtime.loadChunk("server/chunks/ssr/app_ee0e32._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__c2b887._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__3314af._.css");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_7701f0._.js");
runtime.loadChunk("server/chunks/ssr/a7abb_next_dist_client_components_forbidden-error_54953c.js");
runtime.loadChunk("server/chunks/ssr/a7abb_next_dist_client_components_unauthorized-error_a8ad81.js");
runtime.loadChunk("server/chunks/ssr/a7abb_next_4029e2._.js");
runtime.loadChunk("server/chunks/ssr/9c5b9_@auth_core_f4d4eb._.js");
runtime.loadChunk("server/chunks/ssr/96a70_jose_dist_webapi_f83c12._.js");
runtime.loadChunk("server/chunks/ssr/cdf59_zod_lib_index_mjs_a06c28._.js");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_b79f67._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__2f6809._.js");
runtime.loadChunk("server/chunks/ssr/app_008afc._.js");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_f82194._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__cd5a82._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/dashboard/(overview)/page/actions.js { ACTIONS_MODULE0 => \"[project]/app/ui/dashboard/sidenav.tsx [app-rsc] (ecmascript)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/dashboard/(overview)/page { METADATA_0 => \"[project]/app/opengraph-image.png.mjs { IMAGE => \\\"[project]/app/opengraph-image.png [app-rsc] (static)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/app/dashboard/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_6 => \"[project]/app/dashboard/(overview)/loading.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_7 => \"[project]/app/dashboard/(overview)/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
